version: '3'

services:
  app:
    image: golang:1.13
    ports:
      - "8080:8080"
    container_name: golang-test-container
    volumes:
      - ./go:/go
    tty: true
    depends_on:
      - database
    links:
      - database

  database:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: slack-alert
    container_name: golang-docker-db
    ports:
      - 33066:3306
    volumes:
      - golang-docker-data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: golang-docker-pma


# persisted storage
volumes:
  golang-docker-data: